// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconHome: typeof import('./../components/icons/iconHome.vue')['default']
    IconMoon: typeof import('./../components/icons/iconMoon.vue')['default']
    IconSun: typeof import('./../components/icons/iconSun.vue')['default']
    IconUser: typeof import('./../components/icons/iconUser.vue')['default']
    Logo: typeof import('./../components/logo.vue')['default']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NiIcon: typeof import('./../components/NiIcon.vue')['default']
    NImage: typeof import('naive-ui')['NImage']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
